### ISSUE TITLE
https://github.com/symflower/eval-dev-quality/pull/155/files missing a test

### ISSUE THREAD

**Issue by zimmski** [symflower/eval-dev-quality#159]
All change need tests in TDD style. fail first, pass with changes. Same rules as internally.

**Comment by Munsio** [comment]
Well the testcase itself is using `filepath.Join` for the paths so if the test case is run on windows or macos or linux it is using the path separator for that particular OS

**Comment by zimmski** [comment]
What was the reason for changing this then? I thought you said something failed/did not work?

**Comment by Munsio** [comment]
The test case was wrong in the first place as it used hardcoded `/` for paths, because of the hardcoded nature the test succeeded on Windows even if it shouldn't.

By switching the testcase result to use `filepath.Join` instead of the hardcoded versions, it did in fact fail on Windows until I changed the implementation of `TestFilePath` to `filepath.Join` too.
